### PR TITLE
Made isHighlighted reactive

### PR DESCRIPTION
**Pull request by marbetschar**
This addresses https://github.com/antoninbiret/RxEureka/issues/10

### CODE REVIEW

**Comment by antoninbiret** [comment]
Hi @marbetschar. Thanks for this PR. I'm waiting your feedback on #11 before merging this one as it uses the same tricks to avoid the memory leak.

**Comment by antoninbiret** [comment]
@marbetschar Could you add a test case for this new property ? After that this will be good to merge.

**Comment by marbetschar** [comment]
@antoninbiret test case added for `isHighlighted`.

**Comment by antoninbiret** [comment]
Thanks @marbetschar. Merged 👍

**Pull request merged**
